<a href="https://colab.research.google.com/github/baharaaii/DBCourseInha/blob/main/ITS%2C_Midterm%2C_Bahara_Attaii.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import sqlite3

# Connect to a SQLite database (creates a new one if it doesn't exist)
conn = sqlite3.connect('ITS_database.db')
cursor = conn.cursor()

# Create the Customer table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Customer (
  C_ID NVARCHAR(10) PRIMARY KEY NOT NULL,
  C_FName NVARCHAR(26) NOT NULL,
  C_MName NVARCHAR(50),
  C_LName NVARCHAR(26) NOT NULL,
  C_Email NVARCHAR(100) NOT NULL,
  C_PhoneNO INT NOT NULL,
  C_Address NVARCHAR NOT NULL,
  C_DOB DATE NOT NULL,
  C_Sex INT
)
''')
# - The Primary Key (PK) is 'C_ID', it is a string with a 10 character limit
# - C_FName, is the first name of the Customer, it has a character limit of 26, and cannot be null
# - C_MName, is the middle name of the Customer, it has a character limit of 50, and can be null, because not everyone has a middle name
# - C_LName, is the last name of the Customer, it has a character limit of 26, and cannot be null
# - C_Email, is the email of the Customer, it has a character limit of 100 and cannot be null
# - C_PhoneNO, is the phone number of the Customer, an integer with a max of 12 characters and cannot be null
# - C_Address, is the Customers current address, and cannot be null
# - C_DOB, stands for 'date of birth' and is a date value, and cannot be null
# - C_Sex, is the gender of the Customer, an integer with a limit of 6, because it is either 'male' or 'female', and it cannot be null

# Create the Driver table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Driver (
  D_ID INT PRIMARY KEY NOT NULL,
  D_FName NVARCHAR(26) NOT NULL,
  D_MName NVARCHAR(50),
  D_LName NVARCHAR(26) NOT NULL,
  D_Email NVARCHAR(100) NOT NULL,
  D_PhoneNO INT NOT NULL,
  D_Address NVARCHAR NOT NULL,
  D_DOB DATE NOT NULL
)
''')
# - The Primary Key (PK) is 'D_ID', it is an integer with a 12 character limit
# - D_FName, is the first name of the Driver, it has a character limit of 26, and cannot be null
# - D_MName, is the middle name of the Driver, it has a character limit of 50, and can be null, because not everyone has a middle name
# - D_LName, is the last name of the Driver, it has a character limit of 26, and cannot be null
# - D_Email, is the email of the Driver, it has a character limit of 100 and cannot be null
# - D_PhoneNO, is the phone number of the Driver, an integer with a max of 12 characters and cannot be null
# - D_Address, is the Driver's current address, and cannot be null
# - D_DOB, stands for 'date of birth' and is a date value, and cannot be null

# Create the Vehicle table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Vehicle (
  V_ID INT PRIMARY KEY NOT NULL,
  V_Type NVARCHAR(30) NOT NULL,
  V_LicensePlate NVARCHAR(10) NOT NULL,
  V_Capacity INT NOT NULL
)
''')
# - The Primary Key (PK) is 'V_ID', it is an integer with a 16 character limit
# - V_Type is the type of the vehicle, a string with the limit of 30 characters and cannot be null
# - V_LicensePlate is the license plate of the vehicle. a string of max 10 characters and cannot be null
# - V_Capacity is the amount of people a vehicle can hold, an integer that cannot be null

# Create the Route table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Route (
  R_ID INT PRIMARY KEY NOT NULL,
  R_StartLocation NVARCHAR NOT NULL,
  R_EndLocation NVARCHAR NOT NULL,
  R_Distance INT NOT NULL,
  R_ETA DATE NOT NULL,
  Trip_T_ID INT,
  Event_E_ID NVARCHAR(12),
  FOREIGN KEY (Trip_T_ID) REFERENCES Trip (T_ID),
  FOREIGN KEY (Event_E_ID) REFERENCES Event (E_ID)
)
''')
# - The Primary Key (PK) is 'R_ID', it is an integer with a 12 character limit
# - R_StartLocation is the start location of the route, a string that cannot be null
# - R_EndLocation is the end location of the route, a string that cannot be null
# - R_Distance is the distance of the route, an integer which cannot be null
# - R_ETA is the estimated arrival time of the route, a date value and cannot be null
# - Trip_T_ID is a reference to the Trip table
# - Event_E_ID is a reference to the Event table

# Create the Booking table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Booking (
  B_ID INT PRIMARY KEY NOT NULL,
  B_Date DATE NOT NULL,
  Customer_C_ID NVARCHAR(10),
  Payment_P_ID INT,
  Event_E_ID NVARCHAR(12),
  FOREIGN KEY (Customer_C_ID) REFERENCES Customer (C_ID),
  FOREIGN KEY (Payment_P_ID) REFERENCES Payment (P_ID),
  FOREIGN KEY (Event_E_ID) REFERENCES Event (E_ID)
)
''')
# - The Primary Key (PK) is 'B_ID', it is an integer with a 20 character limit
# - B_Date is the date of when the booking takes place, a date type and cannot be null
# - Customer_C_ID is a reference to the Customer table
# - Payment_P_ID is a reference to the Payment table
# - Event_E_ID is a reference to the Event table

# Create the Trip table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Trip (
  T_ID INT PRIMARY KEY NOT NULL,
  T_Date DATE NOT NULL,
  Driver_D_ID INT,
  Vehicle_V_ID INT,
  Booking_B_ID INT,
  Official_O_ID INT,
  FOREIGN KEY (Driver_D_ID) REFERENCES Driver (D_ID),
  FOREIGN KEY (Vehicle_V_ID) REFERENCES Vehicle (V_ID),
  FOREIGN KEY (Booking_B_ID) REFERENCES Booking (B_ID),
  FOREIGN KEY (Official_O_ID) REFERENCES Official (O_ID)
)
''')
# - The Primary Key (PK) is 'T_ID', it is an integer with a 20 character limit
# - T_Date is the date where the trip takes place, a date type and cannot be null
# - Driver_D_ID is a reference to the Driver table
# - Vehicle_V_ID is a reference to the Vehicle table
# - Booking_B_ID is a reference to the Booking table
# - Official_O_ID is a reference to the Official table

# Create the Payment table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Payment (
  P_ID INT PRIMARY KEY NOT NULL,
  P_Invoice NVARCHAR(20) NOT NULL,
  Customer_C_ID NVARCHAR(10),
  FOREIGN KEY (Customer_C_ID) REFERENCES Customer (C_ID)
)
''')
# - The Primary Key (PK) is 'P_ID', it is an integer with a 20 character limit
# - P_Invoice is the invoice of the payment, a string with the character limit of 20 which cannot be null
# - Customer_C_ID is a reference to the Customer table

# Create the Event table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Event (
  E_ID NVARCHAR(12) PRIMARY KEY NOT NULL,
  E_Name NVARCHAR(30) NOT NULL,
  E_Date DATE NOT NULL,
  E_Description NVARCHAR(100) NOT NULL,
  Official_O_ID INT,
  FOREIGN KEY (Official_O_ID) REFERENCES Official (O_ID)
)
''')
# - The Primary Key (PK) is 'E_ID', it is a string with a 12 character limit
# - E_Name is the name of the event, a string with a limit of 30 characters and cannot be null
# - E_Date is the date of the event, a date type and cannot be null
# - E_Description is a description of the event, a string with a limit of 100 characters and cannot be null
# - Official_O_ID is a reference to the Official table

# Create the Official table if it doesn't exist
cursor.execute('''
CREATE TABLE IF NOT EXISTS Official (
  O_ID INT PRIMARY KEY NOT NULL,
  O_FName NVARCHAR(26) NOT NULL,
  O_MName NVARCHAR(50),
  O_LName NVARCHAR(26) NOT NULL,
  O_Role NVARCHAR NOT NULL,
  Event_E_ID NVARCHAR(12),
  FOREIGN KEY (Event_E_ID) REFERENCES Event (E_ID)
)
''')
# - The Primary Key (PK) is 'O_ID', it is an integer and cannot be null
# - O_FName, is the first name of the Official, it has a character limit of 26, and cannot be null
# - O_MName, is the middle name of the Official, it has a character limit of 50, and can be null, because not everyone has a middle name
# - O_LName, is the last name of the Official, it has a character limit of 26, and cannot be null
# - O_Role, is the role of the Official, it is a string and cannot be null
# - Event_E_ID is a reference to the Event table

# Commit the changes and close the connection
conn.commit()
conn.close()